<?php
/**
 * @file
 * Code for the biblio_config feature.
 */

include_once 'biblio_config.features.inc';

/**
 * Implements hook_update_projects_alter().
 */
function biblio_config_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['biblio_config']);
}

// Adds CSS to Views
/**
 * Implements hook_views_pre_render().
 */
function biblio_config_views_pre_render(&$view) {
  $biblio_config_view = array('biblio_config', 'biblio_config');
  if (in_array($view->name, $biblio_config_view)) {
    //drupal_add_js(drupal_get_path('module', 'td_deals') . '/td_deals.js');
//    $biblio_config_module_path = drupal_get_path('module', 'biblio_config');
    //drupal_add_js($contextual_module_path . '/contextual.js');
    drupal_add_css(drupal_get_path('module', 'biblio_config') . '/css/biblio_config.css');
  }
}

// Adds CSS to view display of biblio_config node type but not the edit display
function biblio_config_preprocess_page(&$vars) {
  // Global node.
  $node = menu_get_object();
  if (!empty($node) && $node->type == 'biblio_config' && arg(2) === null) {
    drupal_add_css(drupal_get_path('module', 'biblio_config') . '/css/biblio_config.css');
  }
}

// I don't like this, I would like to add css to the biblio path and nothing else.
function biblio_config_init() {
  global $user, $conf;
  drupal_add_css(drupal_get_path('module', 'biblio_config') . '/css/biblio_config.css');

  if ($user->uid === 0) { // Prevent caching of biblio pages for anonymous users so session variables work and thus filering works
    $base = variable_get('biblio_config_base', 'biblio_config');
    if (drupal_match_path($_GET['q'], "$base\n$base/*"))
      $conf['cache'] = FALSE;
  }
}

// Adding support to discover template files
/**
 * Implements hook_theme_registry_alter()
 **/
function biblio_config_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'biblio_config');
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _biblio_config_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
 */
function _biblio_config_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}
