<?php

/**
 * Implements hook_enable()
 */
function luggage_biblio_enable() {
  db_update('system')
    ->fields(array('weight' => 100000))
    ->condition('type', 'module')
    ->condition('name', 'luggage_biblio')
    ->execute();
  db_update('node_type')
    ->fields(array('name' => 'Publication','description' => 'Use Publication for scholarly content, such as journal papers and books.'))
    ->condition('type', 'module')
    ->condition('name', 'luggage_biblio')
    ->execute();
}